# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            FuzzyBunny Homepage
tagline:          Farzin Mohammadi personal page
description:      'Blog, twitter or a facebok page. A writer always wants to share his/her thoughts <br> Studying Hardware engineering at
                    <a href="http://cse.shirazu.ac.ir" target="_blank">CSE Department of Shiraz University</a> <br>
                    <a href="http:http://aiesec.org/" target="_blank">AIESEC</a> Shiraz LCVP Business Development'
url:              "http://farzinlize.github.io"
baseurl:          ""

author:
  name:           'Farzin Mohammadi'
  url:            https://github.com/farzinlize

paginate:         5

# Custom vars
version:          2.0

github:           https://github.com/farzinlize
  repo:           https://github.com/farzinlize/farzinlize.github.io
